import DragableTaskList from "@/components/dragableTaskList";
import { MapLocator } from "@/components/MapLocator";
// import QuillTextEditor from "../components/QuillTextEditor";
import { TextEditor } from "@/components/TextEditor";
import { TextReader } from "@/components/TextReader";
import Head from "next/head";
import dynamic from "next/dynamic";

const QuillTextEditor = dynamic(() => import("../components/QuillTextEditor"), {
  ssr: false,
  loading: () => {
    return <div>Loading............</div>;
  },
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <MapLocator locations={[]} /> */}
      {/* <DragableTaskList /> */}
      {/* <TextEditor /> */}
      {/* <TextReader /> */}
      <QuillTextEditor />
    </>
  );
}
