import DragableTaskList from "@/components/dragableTaskList";
import { MapLocator } from "@/components/MapLocator";
import { TextEditor } from "@/components/TextEditor";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <MapLocator locations={[]} /> */}
      {/* <DragableTaskList /> */}
      <div style={{ height: "600px", width: "600px" }}>
        <TextEditor />
      </div>
    </>
  );
}
